# Generated by Django 3.0.8 on 2020-07-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addres',
            old_name='name',
            new_name='user',
        ),
    ]
